### PR TITLE
[Backend] Updating identifiers when the diagram is modified

### PR DESCRIPTION
**Pull request by cptanalatriste**
The following events trigger a re-calculation of the item identifiers:

- Adding/Deleting Context.
- Adding/Deleting Strategies.
- Adding/Deleting Property Claims.

The new identifiers are written on the database. If the frontend re-renders the diagram, the ids should be reflected.

DO NOT MERGE UNLESS EXTENSIVE TESTING IS PERFORMED!

**This is an emergency PR for unblocking @RichGriff for next workshop features:** I've manually verified the changes work using the legacy front-end, but further testing is required, specially with the new frontend and corner-cases.

Automated tests are still pending. I will deliver them once the HackWeek is over.

### CODE REVIEW

**Comment by RichGriff** [comment]
@cptanalatriste  We shouldn't be merging this into `main` - it should be into `develop` but not until the frontend dev has been completed

**Comment by cptanalatriste** [comment]
> @cptanalatriste We shouldn't be merging this into `main` - it should be into `develop` but not until the frontend dev has been completed.
> 
> I will take a look at your branch, did you create that branch from `develop` ?

I branched from `main`

**Comment by RichGriff** [comment]
@cptanalatriste ah right okay. Will try and take your branch and merge it into the develop or another working branch to test the changes. 

We'll have to cancel this pull request as we shouldn't be pushing into main unless its a release.

**Comment by kallewesterling** [comment]
Would it be possible for us to do a `git rebase` based on the `ttw-conversion` branch? It may be an easier way than trying to go via the `main` branch, which doesn't have any of the updates on the frontend from Rich?

**Comment by cptanalatriste** [comment]
These functional was already moved into `develop` as part of another PR.

**Pull request closed without merging**
