### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by AoifeHughes**
TODO: 
- [x] Add back links to docs 
- [x] Make changes to case container 
- [x] fix all black colour scheme option
- [x] Fix Grommet Menu items
- [x] Update case creation menu
- [ ] Redesign GitHub interface 
- [x] Remove storing email address for GitHub
- [x] Fix svg stuff https://github.com/alan-turing-institute/AssurancePlatform/issues/284 
- [x] Fix https://github.com/alan-turing-institute/AssurancePlatform/issues/254
- [x] Add comment storing https://github.com/alan-turing-institute/AssurancePlatform/issues/189
    - [x] To database
    - [x] To frontend 
- [ ] address formatting guidance for repos and add documentation on this https://github.com/alan-turing-institute/AssurancePlatform/issues/173
- [x] STOP THE FLICKERING WHEN "LOADING..."

### CODE REVIEW

**Comment by AoifeHughes** [comment]
Screenshot 2023-11-07 at 00 43 45

**Comment by AoifeHughes** [comment]
Screenshot 2023-11-07 at 00 43 51

**Comment by AoifeHughes** [comment]
@kallewesterling I got distracted and went off on trying to do some design stuff, dunno if this fits into current sprint or not, let me know.

**Comment by AoifeHughes** [comment]
https://github.com/indrasat/react-native-fab-action-menu ?

**Comment by AoifeHughes** [comment]
I’m aware of what we’ve said about the editing component needing reworked and I’m thinking of possibilities. I need to refactor caseccontainer.js as it’s way too big a file at this point, anyway, so may as well think a little on this too.

**Comment by AoifeHughes** [comment]
Screenshot 2023-11-07 at 10 10 10
reworked create window

**Comment by AoifeHughes** [comment]
Screenshot 2023-11-07 at 10 12 38
updated case editor

**Comment by AoifeHughes** [comment]
Screenshot 2023-11-07 at 12 01 42
added a comment section

**Comment by AoifeHughes** [comment]
Screenshot 2023-11-07 at 12 56 13
its prettier now

**Comment by chrisdburr** [comment]
> Screenshot 2023-11-07 at 00 43 45

Please can we update the name (site-wide) to `Trustworthy and Ethical Assurance Platform`?

**Comment by chrisdburr** [comment]
> https://github.com/indrasat/react-native-fab-action-menu ?

Looks cool, @AoifeHughes. Where were you thinking of using this?

**Comment by kallewesterling** [comment]
I'm so happy to see these updates! Sorry about being a little bit out of the action currently, due to the Turing Way book dash!

**Comment by AoifeHughes** [comment]
pulling to test

**Comment by kallewesterling** [comment]
Exciting news!

**Pull request merged**
