### PR TITLE
Documentation updates 

### PR DESCRIPTION
**Pull request by AoifeHughes**

### CODE REVIEW

**Comment by AoifeHughes** [comment]
@chrisdburr I saw this branch had a lot of changes and had fallen out of sync a bit with main. I tidied it up a bit so it can be merged whenever you think it's ready!

**Comment by AoifeHughes** [comment]
If you're still adding on your side you'll need a `git pull` on this branch first though as I merged it with main's latest changes.

**Comment by chrisdburr** [comment]
> @chrisdburr I saw this branch had a lot of changes and had fallen out of sync a bit with main. I tidied it up a bit so it can be merged whenever you think it's ready!

Thanks, @aoife. I wasn't planning to merge it just yet, because the drafts will then be compiled into the pages for the site. Probably a good idea to discuss and agree on criteria for merging though.

**Comment by AoifeHughes** [comment]
Okie dokie, I'll change back to a draft for now

**Pull request merged**
